// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "jaxon.app/jaxon/internal/templates"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html class=\"\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templates.Header("Login").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<body class=\"flex h-full py-16\"><main class=\"w-full flex justify-center max-w-md mx-auto p-6\"><div class=\"mt-7 rounded-xl shadow-sm\"><div class=\"card card-bordered bg-base-200 border-neutral p-4 sm:p-7\"><div class=\"text-center mb-4\"><h1 class=\"justify-center text-3xl font-black from-primary to-secondary\">TurboLily</h1></div><div class=\"text-center mb-4\"><h1 class=\"card-title justify-center\">Sign in</h1></div><div><!-- Form --><form method=\"post\" action=\"/auth/login\"><div class=\"grid gap-y-4\"><!-- Form Group --><div><label for=\"email\" class=\"label\">Email address</label><div class=\"relative\"><input type=\"email\" id=\"email\" name=\"email\" autocomplete=\"email\" class=\"input input-bordered\" required aria-describedby=\"email-error\" placeholder=\"Your email address\"><div class=\"hidden absolute inset-y-0 end-0 pointer-events-none pe-3\"><svg class=\"size-5 text-red-500\" width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 16 16\" aria-hidden=\"true\"><path d=\"M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z\"></path></svg></div></div><p class=\"hidden text-xs text-red-600 mt-2\" id=\"email-error\">Please include a valid email address</p></div><!-- End Form Group --><!-- End Checkbox --><button type=\"submit\" class=\"btn btn-primary mt-4\">Send link <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-move-right\"><path d=\"M18 8L22 12L18 16\"></path><path d=\"M2 12H22\"></path></svg></button></div></form><!-- End Form --></div></div></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
