// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"jaxon.app/jaxon/internal/auth/otp"
	"jaxon.app/jaxon/internal/templates"
)

func LoginValidation(otpass *otp.OneTimePass) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html class=\"h-full\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templates.Header("Login Validation").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<body class=\"dark:bg-slate-950 bg-gray-100 flex h-full py-16\"><main class=\"w-full max-w-md mx-auto p-6\"><div class=\"mt-7 bg-white border-gray-200 rounded-xl shadow-sm dark:bg-slate-950\"><div class=\"p-4 sm:p-7\"><div class=\"text-center\"><div class=\"flex justify-center mb-5\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"48\" height=\"48\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-key-round dark:text-teal-700\"><path d=\"M2 18v3c0 .6.4 1 1 1h4v-3h3v-3h2l1.4-1.4a6.5 6.5 0 1 0-4-4Z\"></path> <circle cx=\"16.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\"></circle></svg></div><form action=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL = templ.URL(fmt.Sprintf("/auth/login/magic/%s", otpass.MagicToken))
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var2)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" method=\"POST\"><div class=\"flex space-x-3 justify-center\" data-hs-pin-input=\"\"><input name=\"digit_1\" type=\"text\" class=\"block w-[48px] text-center border-gray-200 rounded-md text-2xl focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900/50 dark:border-slate-800 dark:text-slate-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600\" data-hs-pin-input-item=\"\" autofocus=\"\"> <input name=\"digit_2\" type=\"text\" class=\"block w-[48px] text-center border-gray-200 rounded-md text-2xl focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900/50 dark:border-slate-800 dark:text-slate-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600\" data-hs-pin-input-item=\"\"> <input name=\"digit_3\" type=\"text\" class=\"block w-[48px] text-center border-gray-200 rounded-md text-2xl focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900/50 dark:border-slate-800 dark:text-slate-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600\" data-hs-pin-input-item=\"\"> <input name=\"digit_4\" type=\"text\" class=\"block w-[48px] text-center border-gray-200 rounded-md text-2xl focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900/50 dark:border-slate-800 dark:text-slate-400 dark:placeholder-neutral-500 dark:focus:ring-neutral-600\" data-hs-pin-input-item=\"\"></div><div class=\"mt-3\"><button type=\"submit\" class=\"p-2 border-1 dark:bg-teal-700 rounded-lg dark:text-slate-300\">submit</button></div></form><p class=\"my-3 text-sm text-gray-600 dark:text-gray-400\">Enter your one time passcode here.</p></div></div></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
